### ISSUE TITLE
BYD HVM is shown as HVS.

### ISSUE THREAD

**Issue by teampyt** [bbr111/byd_hvs#1]
BYD HVM is shown as HVS.

**Comment by teampyt** [comment]
.

**Comment by bbr111** [comment]
@teampyt Could you test with an HVM?

**Comment by teampyt** [comment]
Yes, I was confused. I do have a HVM 22.1 but it is shown as HVS.
Another issue. Discharge Tower 1 is missspelled and no unit is shown...
Maybe you want to correct that?

**Comment by teampyt** [comment]
HVM not shown correctly.

**Comment by fhainz** [comment]
Same here. I have an HVM 11.0 and it is shown as HVS.

**Comment by bbr111** [comment]
Need some example output from https://github.com/bbr111/python-bydhvs

**Comment by teampyt** [comment]
Sorry, beyond my knowledge....
Maybe you add an output option, that I could post?
By the way, ver. 0.4.4 does not show any day of Tower 2 anoymore...
