### ISSUE TITLE
Missing units

### ISSUE THREAD

**Issue by tramperb** [bbr111/byd_hvs#3]
With V0.3.1, byd_tower_1_charge_total has the value 8,533,496 Ah but byd_charge_total is 8,533.4 Ah.  I would expect the same value (in a one tower system).

The same issue applies to the two discharge_total entities.  Additionally, the unit of measure is not specified for byd_tower_1_ischarge_total.

edited to add: also the two ETA entities (% efficiency??) don't have units.

**Comment by bbr111** [comment]
Units updated in next release.

**Comment by bbr111** [comment]
checking python_bydhvs for values

**Comment by tramperb** [comment]
BTW, ETA is (charge_total / discharge_total), so it is efficiency.

**Comment by bbr111** [comment]
@tramperb Should we rename it?
I just got it from an iobroker integrtion, they named it ETA

**Comment by tramperb** [comment]
Eta is the Greek letter and is the symbol for energy conversion efficiency (used by the technical & scientific communities - with thanks to Wikipedia :)
Probably leave as is, given it's a standard symbol.
