### ISSUE TITLE
Integration not shown if you are using 2 or 3 HVS tower in parallel

### ISSUE THREAD

**Issue by vasili1979** [bbr111/byd_hvs#6]
Hello, the first Tower (Master) is fine but the 2. and 3. will not shown correctly. What can I do? No additional config possible.

![IMG_6828](https://github.com/user-attachments/assets/ceb9fe56-85ef-441e-aadf-86da49fa03ff)

regards
Daniel

**Comment by teampyt** [comment]
Same here.
Ich könnte Zugriff auf meine 3x7 HVM zu debugzwecken vefügbar machen. Bitte mich anschreiben bei Interesse.
Viele Grüße 
Teampty

**Comment by bbr111** [comment]
@teampyt Sehr gern,
Das sollten wir schnell finden.
Schreib mir am besten mal eine Email, wie ich dich erreichen kann.

**Comment by teampyt** [comment]
Hallo Benjamin,

 

ich bin Klaus.

Ich schalte dir mal den Zugriff auf eine HVM 3x 19,2 kWh frei. Über welchen Port greifst du zu?

Den trage ich dann ein, ja?

Für Rückfragen: 0171 476 5441 

Und schon mal danke für diese tolle Tool! 😊

 

Viele Grüße

Klaus

 

Von: Benjamin ***@***.***> 
Gesendet: Freitag, 29. November 2024 12:51
An: bbr111/byd_hvs ***@***.***>
Cc: teampyt ***@***.***>; Mention ***@***.***>
Betreff: Re: [bbr111/byd_hvs] Integration not shown if you are using 2 or 3 HVS tower in parallel (Issue #6)

 

@teampyt <https://github.com/teampyt>  Sehr gern,
Das sollten wir schnell finden.
Schreib mir am besten mal eine Email, wie ich dich erreichen kann.
